package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoPutRecordInput represents the input for network.habitat.repo.putRecord
type NetworkHabitatRepoPutRecordInput struct {
	Collection string                 `json:"collection"`
	Record     map[string]interface{} `json:"record"`
	Repo       string                 `json:"repo"`
	Rkey       string                 `json:"rkey"`
	Validate   bool                   `json:"validate,omitempty"`
}

// NetworkHabitatRepoPutRecordOutput represents the output for network.habitat.repo.putRecord
type NetworkHabitatRepoPutRecordOutput struct {
	Uri              string `json:"uri"`
	ValidationStatus string `json:"validationStatus,omitempty"`
}
