package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoListRecordsParams represents the input parameters for network.habitat.repo.listRecords
type NetworkHabitatRepoListRecordsParams struct {
	Repo       string `json:"repo"`
	Collection string `json:"collection"`
	Limit      int64  `json:"limit,omitempty"`
	Cursor     string `json:"cursor,omitempty"`
	Reverse    bool   `json:"reverse,omitempty"`
}

// NetworkHabitatRepoListRecordsOutput represents the output for network.habitat.repo.listRecords
type NetworkHabitatRepoListRecordsOutput struct {
	Cursor  string        `json:"cursor,omitempty"`
	Records []interface{} `json:"records"`
}
