package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoGetRecordParams represents the input parameters for network.habitat.repo.getRecord
type NetworkHabitatRepoGetRecordParams struct {
	Collection string `json:"collection"`
	Repo       string `json:"repo"`
	Rkey       string `json:"rkey"`
}

// NetworkHabitatRepoGetRecordOutput represents the output for network.habitat.repo.getRecord
type NetworkHabitatRepoGetRecordOutput struct {
	Uri   string      `json:"uri"`
	Value interface{} `json:"value"`
}
