package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoListRecordsParams represents the input parameters for network.habitat.repo.listRecords
type NetworkHabitatRepoListRecordsParams struct {
	Collection string `json:"collection"`
	Cursor     string `json:"cursor,omitempty"`
	Limit      int64  `json:"limit,omitempty"`
	Repo       string `json:"repo"`
	Reverse    bool   `json:"reverse,omitempty"`
}

// NetworkHabitatRepoListRecordsOutput represents the output for network.habitat.repo.listRecords
type NetworkHabitatRepoListRecordsOutput struct {
	Cursor  string                                `json:"cursor,omitempty"`
	Records []NetworkHabitatRepoListRecordsRecord `json:"records"`
}

// NetworkHabitatRepoListRecordsRecord represents a record object
type NetworkHabitatRepoListRecordsRecord struct {
	Cid   string      `json:"cid"`
	Uri   string      `json:"uri"`
	Value interface{} `json:"value"`
}
