package habitat

// Code generated by lexgen. DO NOT EDIT.

// NetworkHabitatRepoUploadBlobOutput represents the output for network.habitat.repo.uploadBlob
type NetworkHabitatRepoUploadBlobOutput struct {
	Blob interface{} `json:"blob"`
	Cid  string      `json:"cid,omitempty"`
}
